name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag dell_idrac_fan_controller:$(date +%s)
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: tigerblue77/dell_idrac_fan_controller
        tag-custom: latest        
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
